### PR TITLE
docs: condensed the README

### PR DESCRIPTION
**Pull request by LennyAbbas**

### CODE REVIEW

**Review by bharadwajduggaraju — COMMENTED** [review]
Everything seems good, but why'd you get rid of who to ask for questions? Maybe add that back at the end. If you dont want its fine but otherwise it seems good.

**Comment by LennyAbbas** [comment]
i think if someone has questions they should ask on #programming instead of us specifically

**Comment by bharadwajduggaraju** [comment]
> i think if someone has questions they should ask on #programming instead of us specifically

I meant like regarding the commit structure.

**Comment by LennyAbbas** [comment]
? that is what I meant

**Comment by bharadwajduggaraju** [comment]
> ? that is what I meant

ah okay, ill approve that makes sense

**Review by bharadwajduggaraju — APPROVED** [review]

**Review by TiaSinghania — APPROVED** [review]

**Pull request merged**
