### PR TITLE
feat: auton

### PR DESCRIPTION
**Pull request by bharadwajduggaraju**
## Auton Includes:
* auton move command
* getAutonCommand()
* auton plan

### CODE REVIEW

**Comment by LennyAbbas** [comment]
tested `WithRobotRelativeX` and works but needs further testing

**Review by LennyAbbas — DISMISSED** [review]
Why were the docs changed in [this commit](https://github.com/SaintsRobotics/RapidReact2022/commit/8749e0c552f6a419bc309e961c66ac664498b47d). Now its less clear and inconsistent.

**Comment by ProgrammingSR** [comment]
seems to work

**Review by ProgrammingSR — APPROVED** [review]
tested and ready to merge / Leonard

**Pull request merged**
